#!/usr/bin/env node

let monthNames = [
"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
];

let monthNumber = 1;
let name = "L T";

console.log(`My name is ${name}, and my birthday is in the month of ${monthNames[monthNumber-1]}.`);

